At the very beginning, I import everything we need. In this case, I import pandas as the standard "pd" in order to clean and wrangle the data, as well as matplotlib.pyplot as plt and seaborn as sns for when I create the visualizations.

In [488]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Using the pd function .read_csv(), my csv files are made readable by pandas.

In [489]:
student_life_df = pd.read_csv('../Data/AI_Impact_Student_Life_2026.csv')
jobs_df = pd.read_csv('../Data/ai_job_impact.csv')
content_df = pd.read_csv('../Data/Global_AI_Content_Impact_Dataset.csv')

For an initial overlook of the data and how it is shaped, I use .head() and .tail() to see the first and last 5 rows, unless otherwise specified. info() tells me the datatypes of each column as well as how many values are null (if any). Lastly, .shape gives me the dimensions of the table, rows and columns. I created a report function to give me these details all in one go.

In [490]:
def intro_report(list_of_df):
    for df in list_of_df:
        print("Overview of Dataframes")
        print("\nFirst 5 Rows:")
        print(df.head())
        print("\nLast 5 Rows:")
        print(df.tail())
        print('\nNulls and Data Types:')
        print(df.info())
        print('\nRows by Columns')
        print (df.shape)

intro_report([student_life_df, content_df, jobs_df])

Overview of Dataframes

First 5 Rows:
  Student_ID  Age                 Major Primary_AI_Tool  Task_Frequency_Daily  \
0   STU-6019   23  Software Engineering      Gemini Pro                     1
1   STU-6962   22        Modern History  GitHub Copilot                     3
2   STU-2338   18          Data Science      Perplexity                     2
3   STU-1380   19               Biology      Claude 3.5                     5
4   STU-1837   19               Biology      ChatGPT-4o                    10

     Main_Usage_Case  GPA_Baseline  GPA_Post_AI  Time_Saved_Hours_Weekly  \
0     Code Debugging          2.62         2.62                        9
1     Essay Drafting          3.99         4.00                        7
2  Literature Review          2.57         2.57                       15
3     Essay Drafting          2.67         2.87                       12
4     Code Debugging          3.65         3.85                        5

  AI_Ethics_Concern  Career_Confidence_Score
0            Medium                        3
1            Medium                        4
2              High                        7
3               Low                        5
4              High                        9

Last 5 Rows:
     Student_ID  Age                 Major Primary_AI_Tool  \
1495   STU-2711   21        Modern History  GitHub Copilot
1496   STU-4888   21               Biology  GitHub Copilot
1497   STU-0180   23  Software Engineering  GitHub Copilot
1498   STU-4392   23             Fine Arts      Perplexity
1499   STU-4702   23          Data Science      Gemini Pro

      Task_Frequency_Daily Main_Usage_Case  GPA_Baseline  GPA_Post_AI  \
1495                     4   Brainstorming          3.35         3.55
1496                     3  Essay Drafting          3.59         3.89
1497                     8  Code Debugging          3.20         3.40
1498                     6   Brainstorming          3.99         4.00
1499                     4       Exam Prep          3.53         3.43

      Time_Saved_Hours_Weekly AI_Ethics_Concern  Career_Confidence_Score
1495                        7            Medium                        7
1496                       13            Medium                        7
1497                        7               Low                        2
1498                       15               Low                        7
1499                        3            Medium                        8

Nulls and Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               1500 non-null   str
 1   Age                      1500 non-null   int64
 2   Major                    1500 non-null   str
 3   Primary_AI_Tool          1500 non-null   str
 4   Task_Frequency_Daily     1500 non-null   int64
 5   Main_Usage_Case          1500 non-null   str
 6   GPA_Baseline             1500 non-null   float64
 7   GPA_Post_AI              1500 non-null   float64
 8   Time_Saved_Hours_Weekly  1500 non-null   int64
 9   AI_Ethics_Concern        1500 non-null   str
 10  Career_Confidence_Score  1500 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 129.0 KB
None

Rows by Columns
(1500, 11)
Overview of Dataframes

First 5 Rows:
       Country  Year    Industry  AI Adoption Rate (%)  \
0  South Korea  2022       Media                 44.29
1        China  2025       Legal                 34.75
2          USA  2022  Automotive                 81.06
3       France  2021       Legal                 85.24
4       France  2021      Gaming                 78.95

   AI-Generated Content Volume (TBs per year)  Job Loss Due to AI (%)  \
0                                       33.09                   16.77
1                                       66.74                   46.89
2                                       96.13                   10.66
3                                       93.76                   27.70
4                                       45.62                   17.45

   Revenue Increase Due to AI (%)  Human-AI Collaboration Rate (%)  \
0                           46.12                            74.79
1                           52.46                            26.17
2                           45.60                            39.66
3                           78.24                            29.45
4                            1.05                            21.70

  Top AI Tools Used Regulation Status  Consumer Trust in AI (%)  \
0              Bard            Strict                     40.77
1            DALL-E            Strict                     35.67
2  Stable Diffusion          Moderate                     54.47
3            Claude          Moderate                     51.84
4        Midjourney            Strict                     41.77

   Market Share of AI Companies (%)
0                             18.73
1                             35.02
2                             22.76
3                              1.93
4                             21.41

Last 5 Rows:
         Country  Year    Industry  AI Adoption Rate (%)  \
195      Germany  2021  Automotive                 89.44
196      Germany  2020       Media                 70.11
197       France  2023   Marketing                 65.77
198    Australia  2023  Automotive                 45.35
199  South Korea  2020  Healthcare                 10.53

     AI-Generated Content Volume (TBs per year)  Job Loss Due to AI (%)  \
195                                       52.98                   48.47
196                                       28.26                   27.62
197                                       49.83                   39.94
198                                       20.49                   33.21
199                                       20.97                   23.64

     Revenue Increase Due to AI (%)  Human-AI Collaboration Rate (%)  \
195                           12.14                            30.60
196                           57.86                            58.71
197                           79.44                            43.73
198                           50.50                            41.73
199                           34.27                            45.67

    Top AI Tools Used Regulation Status  Consumer Trust in AI (%)  \
195            DALL-E           Lenient                     77.21
196            DALL-E            Strict                     78.74
197         Synthesia           Lenient                     81.58
198            Claude            Strict                     47.42
199  Stable Diffusion          Moderate                     58.52

     Market Share of AI Companies (%)
195                             44.35
196                             31.73
197                             14.62
198                             43.11
199                             33.37

Nulls and Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     200 non-null    str
 1   Year                                        200 non-null    int64
 2   Industry                                    200 non-null    str
 3   AI Adoption Rate (%)                        200 non-null    float64
 4   AI-Generated Content Volume (TBs per year)  200 non-null    float64
 5   Job Loss Due to AI (%)                      200 non-null    float64
 6   Revenue Increase Due to AI (%)              200 non-null    float64
 7   Human-AI Collaboration Rate (%)             200 non-null    float64
 8   Top AI Tools Used                           200 non-null    str
 9   Regulation Status                           200 non-null    str
 10  Consumer Trust in AI (%)                    200 non-null    float64
 11  Market Share of AI Companies (%)            200 non-null    float64
dtypes: float64(7), int64(1), str(4)
memory usage: 18.9 KB
None

Rows by Columns
(200, 12)
Overview of Dataframes

First 5 Rows:
  Employee_ID  Age  Gender Education_Level       Industry           Job_Role  \
0       E0001   50  Female        Bachelor      Marketing    Content Creator
1       E0002   45    Male     High School  Manufacturing  Quality Inspector
2       E0003   51  Female          Master             IT    DevOps Engineer
3       E0004   48    Male             PhD      Education            Teacher
4       E0005   24    Male        Bachelor     Healthcare             Doctor

   Years_Experience AI_Adoption_Level Automation_Risk Upskilling_Required  \
0                26              High            High                 Yes
1                19               Low             Low                 Yes
2                28            Medium          Medium                 Yes
3                24            Medium          Medium                 Yes
4                 0              High          Medium                  No

   Salary_Before_AI  Salary_After_AI Job_Status  Work_Hours_Per_Week  \
0            106820            95455   Replaced                   45
1             74131            72013  Unchanged                   36
2             35311            42290   Modified                   46
3            114478           107820   Modified                   50
4             33890            40945   Modified                   52

  Remote_Work  Job_Satisfaction  Productivity_Change_%
0          No                 5                 -10.64
1         Yes                 6                  19.05
2         Yes                 3                  17.05
3          No                 9                  -2.47
4         Yes                 6                   7.03

Last 5 Rows:
     Employee_ID  Age  Gender Education_Level    Industry            Job_Role  \
1995       E1996   55   Other             PhD  Healthcare          Technician
1996       E1997   31    Male             PhD     Finance  Investment Analyst
1997       E1998   43  Female        Bachelor      Retail             Cashier
1998       E1999   43  Female        Bachelor   Marketing    Digital Marketer
1999       E2000   23   Other          Master   Marketing      SEO Specialist

      Years_Experience AI_Adoption_Level Automation_Risk Upskilling_Required  \
1995                30            Medium             Low                 Yes
1996                 9              High          Medium                 Yes
1997                17              High            High                  No
1998                20            Medium             Low                  No
1999                 0              High            High                 Yes

      Salary_Before_AI  Salary_After_AI Job_Status  Work_Hours_Per_Week  \
1995             99082           101090  Unchanged                   52
1996             32379            44653   Modified                   52
1997             53424            74715   Modified                   49
1998             57821            68499  Unchanged                   41
1999             33830            34809   Modified                   37

     Remote_Work  Job_Satisfaction  Productivity_Change_%
1995         Yes                 7                  25.67
1996         Yes                 8                   9.38
1997         Yes                 6                  -0.57
1998          No                 9                   9.31
1999         Yes                 9                  24.40

Nulls and Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            2000 non-null   str
 1   Age                    2000 non-null   int64
 2   Gender                 2000 non-null   str
 3   Education_Level        2000 non-null   str
 4   Industry               2000 non-null   str
 5   Job_Role               2000 non-null   str
 6   Years_Experience       2000 non-null   int64
 7   AI_Adoption_Level      2000 non-null   str
 8   Automation_Risk        2000 non-null   str
 9   Upskilling_Required    2000 non-null   str
 10  Salary_Before_AI       2000 non-null   int64
 11  Salary_After_AI        2000 non-null   int64
 12  Job_Status             2000 non-null   str
 13  Work_Hours_Per_Week    2000 non-null   int64
 14  Remote_Work            2000 non-null   str
 15  Job_Satisfaction       2000 non-null   int64
 16  Productivity_Change_%  2000 non-null   float64
dtypes: float64(1), int64(6), str(10)
memory usage: 265.8 KB
None

Rows by Columns
(2000, 17)

In [491]:
def standardize(list_of_df):
    for df in list_of_df:
        df.columns = df.columns.str.lower().str.replace(" ", "_")

standardize([student_life_df, content_df, jobs_df])

In [492]:
student_life_df

,student_id,age,major,primary_ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9
...,...,...,...,...,...,...,...,...,...,...,...
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8

I selected these two columns specifically so I could better see a broad overview of the effect of AI on GPA.

In [493]:
student_life_df[['gpa_baseline', 'gpa_post_ai']]

      gpa_baseline  gpa_post_ai
0             2.62         2.62
1             3.99         4.00
2             2.57         2.57
3             2.67         2.87
4             3.65         3.85
...            ...          ...
1495          3.35         3.55
1496          3.59         3.89
1497          3.20         3.40
1498          3.99         4.00
1499          3.53         3.43

[1500 rows x 2 columns]

I decided to use boolean indexing here to filter with conditions to find the amount of students whos GPA grew, declined, and stayed the same. Here I can see that if we just look at GPA's, it will show that AI might be helping students get higher GPA's.

In [494]:
gpa_growth_df = student_life_df[student_life_df['gpa_baseline'] < student_life_df['gpa_post_ai']]
gpa_growth_df.shape

(894, 11)

In [495]:
gpa_decline_df = student_life_df[student_life_df['gpa_baseline'] > student_life_df['gpa_post_ai']]
gpa_decline_df.shape

(301, 11)

In [496]:
gpa_same_df = student_life_df[student_life_df['gpa_baseline'] == student_life_df['gpa_post_ai']]
gpa_same_df.shape

(305, 11)

.describe() gives me the statistics of the values represented by integers. value_counts() tells me how many rows include a given value as a result. From these, I can glean that the most common age in this dataset is 21, the GPA does increase on average, and the most used AI tool is GitHub Copilot.

In [497]:
student_life_df.describe()

,age,task_frequency_daily,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,career_confidence_score
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000,1500.000000
mean,21.494000,5.407333,3.256853,3.344587,8.51000,5.417333
std,2.297277,2.905462,0.430583,0.437409,4.07148,2.844977
min,18.000000,1.000000,2.500000,2.400000,2.00000,1.000000
25%,20.000000,3.000000,2.880000,2.980000,5.00000,3.000000
50%,21.000000,5.000000,3.260000,3.360000,9.00000,5.000000
75%,23.000000,8.000000,3.620000,3.710000,12.00000,8.000000
max,25.000000,10.000000,4.000000,4.000000,15.00000,10.000000

In [498]:
student_life_df['primary_ai_tool'].value_counts()

primary_ai_tool
GitHub Copilot    311
Gemini Pro        302
Perplexity        302
Claude 3.5        297
ChatGPT-4o        288
Name: count, dtype: int64

In [499]:
content_df['top_ai_tools_used'].value_counts()

top_ai_tools_used
Midjourney          37
Claude              31
ChatGPT             31
Stable Diffusion    27
DALL-E              26
Bard                24
Synthesia           24
Name: count, dtype: int64

In [500]:
jobs_df.describe()

,age,years_experience,salary_before_ai,salary_after_ai,work_hours_per_week,job_satisfaction,productivity_change_%
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000
mean,40.558000,16.663500,73942.072500,78428.642500,44.85100,6.020500,9.785820
std,10.786418,10.746675,26055.823793,29351.599013,5.71254,2.006263,17.187882
min,22.000000,0.000000,30036.000000,24447.000000,35.00000,3.000000,-19.990000
25%,32.000000,8.000000,51665.500000,54086.750000,40.00000,4.000000,-5.355000
50%,40.000000,16.000000,74620.000000,76820.500000,45.00000,6.000000,9.850000
75%,50.000000,26.000000,95418.250000,100730.250000,50.00000,8.000000,24.582500
max,59.000000,37.000000,119976.000000,161745.000000,54.00000,9.000000,39.990000

I was curious about how each employee would qualify in terms of years of experience, and this value would be easy to understand if used in a visual, so I created a function for showing specifically what a person's experience would lead them to apply for in the future.

In [501]:
def categorize_experience(years_experience):
    if years_experience <= 2:
        return 'Entry Level'
    elif years_experience >= 3 and years_experience < 5:
        return 'Mid Level'
    else:
        return 'Senior'

jobs_df['experience_level'] = jobs_df['years_experience'].apply(categorize_experience)
jobs_df

,employee_id,age,gender,education_level,industry,job_role,years_experience,ai_adoption_level,automation_risk,upskilling_required,salary_before_ai,salary_after_ai,job_status,work_hours_per_week,remote_work,job_satisfaction,productivity_change_%,experience_level
0,E0001,50,Female,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior
1,E0002,45,Male,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior
2,E0003,51,Female,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior
3,E0004,48,Male,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior
4,E0005,24,Male,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,E1996,55,Other,PhD,Healthcare,Technician,30,Medium,Low,Yes,99082,101090,Unchanged,52,Yes,7,25.67,Senior
1996,E1997,31,Male,PhD,Finance,Investment Analyst,9,High,Medium,Yes,32379,44653,Modified,52,Yes,8,9.38,Senior
1997,E1998,43,Female,Bachelor,Retail,Cashier,17,High,High,No,53424,74715,Modified,49,Yes,6,-0.57,Senior
1998,E1999,43,Female,Bachelor,Marketing,Digital Marketer,20,Medium,Low,No,57821,68499,Unchanged,41,No,9,9.31,Senior
1999,E2000,23,Other,Master,Marketing,SEO Specialist,0,High,High,Yes,33830,34809,Modified,37,Yes,9,24.40,Entry Level

I want to have AI Adoption Rate Levels for both jobs_df and content_df in order to compare them both, so I created a column for AI Adoption Rate (%) in content_df to match the one in jobs_df.

In [502]:
def categorize_adoption_rate(adoption_rate):
    if adoption_rate <= 33.33:
        return 'Low'
    elif adoption_rate >= 33.34 and adoption_rate <= 66.66:
        return 'Medium'
    else:
        return 'High'

content_df['ai_adoption_level'] = content_df['ai_adoption_rate_(%)'].apply(categorize_adoption_rate)
content_df

,country,year,industry,ai_adoption_rate_(%),ai-generated_content_volume_(tbs_per_year),job_loss_due_to_ai_(%),revenue_increase_due_to_ai_(%),human-ai_collaboration_rate_(%),top_ai_tools_used,regulation_status,consumer_trust_in_ai_(%),market_share_of_ai_companies_(%),ai_adoption_level
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73,Medium
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02,Medium
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76,High
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93,High
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35,High
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73,High
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62,Medium
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11,Medium
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37,Low

This dataset did not require the use of .drop(), but I wanted to practice using it in this analysis.

In [503]:
jobs_df = jobs_df.drop('gender', axis=1)
jobs_df

,employee_id,age,education_level,industry,job_role,years_experience,ai_adoption_level,automation_risk,upskilling_required,salary_before_ai,salary_after_ai,job_status,work_hours_per_week,remote_work,job_satisfaction,productivity_change_%,experience_level
0,E0001,50,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior
1,E0002,45,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior
2,E0003,51,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior
3,E0004,48,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior
4,E0005,24,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,E1996,55,PhD,Healthcare,Technician,30,Medium,Low,Yes,99082,101090,Unchanged,52,Yes,7,25.67,Senior
1996,E1997,31,PhD,Finance,Investment Analyst,9,High,Medium,Yes,32379,44653,Modified,52,Yes,8,9.38,Senior
1997,E1998,43,Bachelor,Retail,Cashier,17,High,High,No,53424,74715,Modified,49,Yes,6,-0.57,Senior
1998,E1999,43,Bachelor,Marketing,Digital Marketer,20,Medium,Low,No,57821,68499,Unchanged,41,No,9,9.31,Senior
1999,E2000,23,Master,Marketing,SEO Specialist,0,High,High,Yes,33830,34809,Modified,37,Yes,9,24.40,Entry Level

In order to maintain consistency between student_life_df['Primary_AI_Tool'] and content_df['Top AI Tools Used']. While we may lose a small amount of specificity in the model version, we won't be altering the statistics by doing so, since there isn't ChatGPT and ChatGPT-4o.

In [504]:
student_life_df['primary_ai_tool'] = student_life_df['primary_ai_tool'].replace({'Claude 3.5': 'Claude', 'ChatGPT-4o': 'ChatGPT'})
student_life_df['primary_ai_tool'].value_counts()

primary_ai_tool
GitHub Copilot    311
Gemini Pro        302
Perplexity        302
Claude            297
ChatGPT           288
Name: count, dtype: int64

isnull() and .sum() tells me which values if any are null/empty, and how many nulls there are.

In [505]:
student_life_df.isnull()

,student_id,age,major,primary_ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1495,False,False,False,False,False,False,False,False,False,False,False
1496,False,False,False,False,False,False,False,False,False,False,False
1497,False,False,False,False,False,False,False,False,False,False,False
1498,False,False,False,False,False,False,False,False,False,False,False
1499,False,False,False,False,False,False,False,False,False,False,False

In [506]:
student_life_df.isnull().sum()

student_id                 0
age                        0
major                      0
primary_ai_tool            0
task_frequency_daily       0
main_usage_case            0
gpa_baseline               0
gpa_post_ai                0
time_saved_hours_weekly    0
ai_ethics_concern          0
career_confidence_score    0
dtype: int64

.dtypes tells me what data types the columns hold, and if I wanted to change any of them I could use .astype(). For example: 

jobs_df['Productivity_Change_%'] = jobs_df['Productivity_Change_%'].astype(int64)

pd.to_datetime can be used to change dates/times to a specific datatype. If this dataset had a column to use this on, it would look like this:

jobs_df['Date'] = pd.to_datetime(jobs_df['Date'] format='%m/%d/%Y')

In [507]:
jobs_df.dtypes

employee_id                  str
age                        int64
education_level              str
industry                     str
job_role                     str
years_experience           int64
ai_adoption_level            str
automation_risk              str
upskilling_required          str
salary_before_ai           int64
salary_after_ai            int64
job_status                   str
work_hours_per_week        int64
remote_work                  str
job_satisfaction           int64
productivity_change_%    float64
experience_level             str
dtype: object

I can tell with .duplicated() and .sum() that there are no duplicated rows in this dataset. By using the function on just one column, one that I know will have duplicates, I can see that the 6 values in the Major column are repeated 1494 times. If there were a reason to drop duplicated, I would use .drop_duplicates()

In [508]:
duplicate_sum = student_life_df.duplicated().sum()

print(duplicate_sum)

0

In [509]:
duplicate_sum = student_life_df.duplicated(subset='major').sum()

print(duplicate_sum)

1494

In order for me to be able to merge Primary_AI_Tool and Top AI Tools Used, I had to name them something similar, which I decided was going to be "AI Tool".

In [510]:
content_df.rename(columns={'top_ai_tools_used': 'ai_tool'}, inplace=True)
content_df

,country,year,industry,ai_adoption_rate_(%),ai-generated_content_volume_(tbs_per_year),job_loss_due_to_ai_(%),revenue_increase_due_to_ai_(%),human-ai_collaboration_rate_(%),ai_tool,regulation_status,consumer_trust_in_ai_(%),market_share_of_ai_companies_(%),ai_adoption_level
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73,Medium
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02,Medium
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76,High
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93,High
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35,High
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73,High
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62,Medium
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11,Medium
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37,Low

In [511]:
student_life_df.rename(columns={'primary_ai_tool': 'ai_tool'}, inplace=True)
student_life_df

,student_id,age,major,ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT,10,Code Debugging,3.65,3.85,5,High,9
...,...,...,...,...,...,...,...,...,...,...,...
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8

In [512]:
student_life_df.sort_values(by=['age', 'major'], ascending=[True, False])

,student_id,age,major,ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score
75,STU-3046,18,Software Engineering,Gemini Pro,2,Exam Prep,3.18,3.18,8,Medium,7
134,STU-5360,18,Software Engineering,Gemini Pro,8,Exam Prep,3.48,3.48,3,Medium,5
157,STU-5053,18,Software Engineering,GitHub Copilot,5,Exam Prep,2.60,2.70,9,High,6
159,STU-3925,18,Software Engineering,Gemini Pro,7,Literature Review,3.23,3.33,3,Medium,2
172,STU-2366,18,Software Engineering,GitHub Copilot,5,Code Debugging,2.54,2.44,9,Medium,4
...,...,...,...,...,...,...,...,...,...,...,...
1330,STU-1586,25,Biology,GitHub Copilot,9,Code Debugging,2.67,2.87,3,High,3
1355,STU-3395,25,Biology,Perplexity,10,Brainstorming,3.45,3.75,9,High,6
1373,STU-6943,25,Biology,Gemini Pro,2,Code Debugging,3.21,3.41,3,High,3
1395,STU-4929,25,Biology,Claude,4,Essay Drafting,3.84,3.84,3,Low,10
1459,STU-5264,25,Biology,Gemini Pro,4,Exam Prep,3.23,3.23,12,Medium,8

In [513]:
student_life_df.sort_index(ascending = False)

,student_id,age,major,ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7
...,...,...,...,...,...,...,...,...,...,...,...
4,STU-1837,19,Biology,ChatGPT,10,Code Debugging,3.65,3.85,5,High,9
3,STU-1380,19,Biology,Claude,5,Essay Drafting,2.67,2.87,12,Low,5
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3

I used the dataframes I made before to see which Primary AI Tool had the worst/best post-AI GPA on average.

In [514]:
gpa_growth_df.groupby(student_life_df['ai_tool'])['gpa_post_ai'].mean()

ai_tool
ChatGPT           3.439773
Claude            3.458671
Gemini Pro        3.486872
GitHub Copilot    3.426902
Perplexity        3.433352
Name: gpa_post_ai, dtype: float64

In [515]:
gpa_decline_df.groupby(student_life_df['ai_tool'])['gpa_post_ai'].mean()

ai_tool
ChatGPT           3.217647
Claude            3.042069
Gemini Pro        3.193913
GitHub Copilot    3.109219
Perplexity        3.161017
Name: gpa_post_ai, dtype: float64

In [516]:
round(gpa_growth_df.groupby(['major', 'main_usage_case'])['gpa_post_ai'].mean(), 2)

major                    main_usage_case
Biology                  Brainstorming        3.58
                         Code Debugging       3.51
                         Essay Drafting       3.54
                         Exam Prep            3.50
                         Literature Review    3.36
Business Administration  Brainstorming        3.37
                         Code Debugging       3.47
                         Essay Drafting       3.44
                         Exam Prep            3.45
                         Literature Review    3.43
Data Science             Brainstorming        3.52
                         Code Debugging       3.42
                         Essay Drafting       3.36
                         Exam Prep            3.51
                         Literature Review    3.38
Fine Arts                Brainstorming        3.36
                         Code Debugging       3.45
                         Essay Drafting       3.39
                         Exam Prep            3.49
                         Literature Review    3.48
Modern History           Brainstorming        3.40
                         Code Debugging       3.45
                         Essay Drafting       3.55
                         Exam Prep            3.41
                         Literature Review    3.38
Software Engineering     Brainstorming        3.47
                         Code Debugging       3.47
                         Essay Drafting       3.50
                         Exam Prep            3.30
                         Literature Review    3.38
Name: gpa_post_ai, dtype: float64

In [517]:
jobs_df.groupby('industry')['productivity_change_%'].agg(['min', 'mean', 'max'])

                 min       mean    max
industry
Education     -19.99  10.014505  39.83
Finance       -19.58   9.565767  39.90
Healthcare    -19.88   9.307259  39.82
IT            -19.91   9.061074  39.99
Manufacturing -19.93  10.697390  39.97
Marketing     -19.77  10.332527  39.91
Retail        -19.92   9.512878  39.86

In [518]:
student_life_df.groupby([student_life_df['ai_tool'], 'main_usage_case']).agg({
    'time_saved_hours_weekly': 'mean',
    'task_frequency_daily': 'count'

})

                                  time_saved_hours_weekly  \
ai_tool        main_usage_case
ChatGPT        Brainstorming                     8.038462
               Code Debugging                    7.897959
               Essay Drafting                    8.666667
               Exam Prep                         8.376812
               Literature Review                 8.545455
Claude         Brainstorming                     8.826923
               Code Debugging                    8.604167
               Essay Drafting                    8.490909
               Exam Prep                         7.970588
               Literature Review                 7.810811
Gemini Pro     Brainstorming                     8.553846
               Code Debugging                    8.920000
               Essay Drafting                    9.211538
               Exam Prep                         8.586207
               Literature Review                 7.958333
GitHub Copilot Brainstorming                     8.126984
               Code Debugging                    7.406780
               Essay Drafting                    8.677966
               Exam Prep                         8.813559
               Literature Review                 9.070423
Perplexity     Brainstorming                     9.648148
               Code Debugging                    8.706897
               Essay Drafting                    8.791667
               Exam Prep                         8.500000
               Literature Review                 8.666667

                                  task_frequency_daily
ai_tool        main_usage_case
ChatGPT        Brainstorming                        52
               Code Debugging                       49
               Essay Drafting                       63
               Exam Prep                            69
               Literature Review                    55
Claude         Brainstorming                        52
               Code Debugging                       48
               Essay Drafting                       55
               Exam Prep                            68
               Literature Review                    74
Gemini Pro     Brainstorming                        65
               Code Debugging                       50
               Essay Drafting                       52
               Exam Prep                            87
               Literature Review                    48
GitHub Copilot Brainstorming                        63
               Code Debugging                       59
               Essay Drafting                       59
               Exam Prep                            59
               Literature Review                    71
Perplexity     Brainstorming                        54
               Code Debugging                       58
               Essay Drafting                       72
               Exam Prep                            58
               Literature Review                    60

In [519]:
content_df.dtypes

country                                           str
year                                            int64
industry                                          str
ai_adoption_rate_(%)                          float64
ai-generated_content_volume_(tbs_per_year)    float64
job_loss_due_to_ai_(%)                        float64
revenue_increase_due_to_ai_(%)                float64
human-ai_collaboration_rate_(%)               float64
ai_tool                                           str
regulation_status                                 str
consumer_trust_in_ai_(%)                      float64
market_share_of_ai_companies_(%)              float64
ai_adoption_level                                 str
dtype: object

In [520]:
def create_list(unique_dfs):
    return pd.concat(unique_dfs).unique()
domain_list = create_list([student_life_df['major'], jobs_df['industry'], content_df['industry']])
domain_list

<StringArray>
[   'Software Engineering',          'Modern History',
            'Data Science',                 'Biology',
 'Business Administration',               'Fine Arts',
               'Marketing',           'Manufacturing',
                      'IT',               'Education',
              'Healthcare',                 'Finance',
                  'Retail',                   'Media',
                   'Legal',              'Automotive',
                  'Gaming']
Length: 17, dtype: str

In [521]:
def makedf(col_name, list_name):
    return pd.DataFrame({col_name: list(list_name)})

domains_df = makedf('domain_name', domain_list)
domains_df

                domain_name
0      Software Engineering
1            Modern History
2              Data Science
3                   Biology
4   Business Administration
5                 Fine Arts
6                 Marketing
7             Manufacturing
8                        IT
9                 Education
10               Healthcare
11                  Finance
12                   Retail
13                    Media
14                    Legal
15               Automotive
16                   Gaming

In [522]:
def add_id(df_name, col_name):
    df_name[col_name] = range(1, len(df_name) + 1)
    return df_name
add_id(domains_df, 'domain_id')

                domain_name  domain_id
0      Software Engineering          1
1            Modern History          2
2              Data Science          3
3                   Biology          4
4   Business Administration          5
5                 Fine Arts          6
6                 Marketing          7
7             Manufacturing          8
8                        IT          9
9                 Education         10
10               Healthcare         11
11                  Finance         12
12                   Retail         13
13                    Media         14
14                    Legal         15
15               Automotive         16
16                   Gaming         17

In [523]:
ai_tools_list = create_list([student_life_df['ai_tool'], content_df['ai_tool']])

In [524]:
ai_tools_df = makedf('ai_tool', ai_tools_list)

In [525]:
add_id(ai_tools_df, 'ai_tool_id')

            ai_tool  ai_tool_id
0        Gemini Pro           1
1    GitHub Copilot           2
2        Perplexity           3
3            Claude           4
4           ChatGPT           5
5              Bard           6
6            DALL-E           7
7  Stable Diffusion           8
8        Midjourney           9
9         Synthesia          10

In [526]:
domains_map = dict(zip(domains_df['domain_name'], domains_df['domain_id']))
def fkmapping(df_name, col_name, col_name2, map_name):
    df_name[col_name] = df_name[col_name2].map(map_name)
    return df_name

fkmapping(student_life_df, 'domain_id', 'major', domains_map)

,student_id,age,major,ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score,domain_id
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3,1
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4,2
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7,3
3,STU-1380,19,Biology,Claude,5,Essay Drafting,2.67,2.87,12,Low,5,4
4,STU-1837,19,Biology,ChatGPT,10,Code Debugging,3.65,3.85,5,High,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7,2
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7,4
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2,1
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7,6
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8,3

In [527]:
fkmapping(jobs_df, 'domain_id', 'industry', domains_map)

,employee_id,age,education_level,industry,job_role,years_experience,ai_adoption_level,automation_risk,upskilling_required,salary_before_ai,salary_after_ai,job_status,work_hours_per_week,remote_work,job_satisfaction,productivity_change_%,experience_level,domain_id
0,E0001,50,Bachelor,Marketing,Content Creator,26,High,High,Yes,106820,95455,Replaced,45,No,5,-10.64,Senior,7
1,E0002,45,High School,Manufacturing,Quality Inspector,19,Low,Low,Yes,74131,72013,Unchanged,36,Yes,6,19.05,Senior,8
2,E0003,51,Master,IT,DevOps Engineer,28,Medium,Medium,Yes,35311,42290,Modified,46,Yes,3,17.05,Senior,9
3,E0004,48,PhD,Education,Teacher,24,Medium,Medium,Yes,114478,107820,Modified,50,No,9,-2.47,Senior,10
4,E0005,24,Bachelor,Healthcare,Doctor,0,High,Medium,No,33890,40945,Modified,52,Yes,6,7.03,Entry Level,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,E1996,55,PhD,Healthcare,Technician,30,Medium,Low,Yes,99082,101090,Unchanged,52,Yes,7,25.67,Senior,11
1996,E1997,31,PhD,Finance,Investment Analyst,9,High,Medium,Yes,32379,44653,Modified,52,Yes,8,9.38,Senior,12
1997,E1998,43,Bachelor,Retail,Cashier,17,High,High,No,53424,74715,Modified,49,Yes,6,-0.57,Senior,13
1998,E1999,43,Bachelor,Marketing,Digital Marketer,20,Medium,Low,No,57821,68499,Unchanged,41,No,9,9.31,Senior,7
1999,E2000,23,Master,Marketing,SEO Specialist,0,High,High,Yes,33830,34809,Modified,37,Yes,9,24.40,Entry Level,7

In [528]:
fkmapping(content_df, 'domain_id', 'industry', domains_map)

,country,year,industry,ai_adoption_rate_(%),ai-generated_content_volume_(tbs_per_year),job_loss_due_to_ai_(%),revenue_increase_due_to_ai_(%),human-ai_collaboration_rate_(%),ai_tool,regulation_status,consumer_trust_in_ai_(%),market_share_of_ai_companies_(%),ai_adoption_level,domain_id
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73,Medium,14
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02,Medium,15
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76,High,16
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93,High,15
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41,High,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35,High,16
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73,High,14
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62,Medium,7
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11,Medium,16
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37,Low,11

In [529]:
ai_tools_map = dict(zip(ai_tools_df['ai_tool'], ai_tools_df['ai_tool_id']))
fkmapping(student_life_df, 'ai_tool_id', 'ai_tool', ai_tools_map)

,student_id,age,major,ai_tool,task_frequency_daily,main_usage_case,gpa_baseline,gpa_post_ai,time_saved_hours_weekly,ai_ethics_concern,career_confidence_score,domain_id,ai_tool_id
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3,1,1
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4,2,2
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7,3,3
3,STU-1380,19,Biology,Claude,5,Essay Drafting,2.67,2.87,12,Low,5,4,4
4,STU-1837,19,Biology,ChatGPT,10,Code Debugging,3.65,3.85,5,High,9,4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,STU-2711,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7,2,2
1496,STU-4888,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7,4,2
1497,STU-0180,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2,1,2
1498,STU-4392,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7,6,3
1499,STU-4702,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8,3,1

In [530]:
fkmapping(content_df, 'ai_tool_id', 'ai_tool', ai_tools_map)

,country,year,industry,ai_adoption_rate_(%),ai-generated_content_volume_(tbs_per_year),job_loss_due_to_ai_(%),revenue_increase_due_to_ai_(%),human-ai_collaboration_rate_(%),ai_tool,regulation_status,consumer_trust_in_ai_(%),market_share_of_ai_companies_(%),ai_adoption_level,domain_id,ai_tool_id
0,South Korea,2022,Media,44.29,33.09,16.77,46.12,74.79,Bard,Strict,40.77,18.73,Medium,14,6
1,China,2025,Legal,34.75,66.74,46.89,52.46,26.17,DALL-E,Strict,35.67,35.02,Medium,15,7
2,USA,2022,Automotive,81.06,96.13,10.66,45.60,39.66,Stable Diffusion,Moderate,54.47,22.76,High,16,8
3,France,2021,Legal,85.24,93.76,27.70,78.24,29.45,Claude,Moderate,51.84,1.93,High,15,4
4,France,2021,Gaming,78.95,45.62,17.45,1.05,21.70,Midjourney,Strict,41.77,21.41,High,17,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,Germany,2021,Automotive,89.44,52.98,48.47,12.14,30.60,DALL-E,Lenient,77.21,44.35,High,16,7
196,Germany,2020,Media,70.11,28.26,27.62,57.86,58.71,DALL-E,Strict,78.74,31.73,High,14,7
197,France,2023,Marketing,65.77,49.83,39.94,79.44,43.73,Synthesia,Lenient,81.58,14.62,Medium,7,10
198,Australia,2023,Automotive,45.35,20.49,33.21,50.50,41.73,Claude,Strict,47.42,43.11,Medium,16,4
199,South Korea,2020,Healthcare,10.53,20.97,23.64,34.27,45.67,Stable Diffusion,Moderate,58.52,33.37,Low,11,8

In [531]:
avg_satisfaction = jobs_df.groupby('domain_id')['job_satisfaction'].mean()
avg_loss = content_df.groupby('domain_id')['job_loss_due_to_ai_(%)'].mean()
avg_trust = content_df.groupby('domain_id')['consumer_trust_in_ai_(%)'].mean()

fkmapping(domains_df, 'job_satisfaction', 'domain_id', avg_satisfaction)
fkmapping(domains_df, 'job_loss', 'domain_id', avg_loss)
fkmapping(domains_df, 'consumer_trust', 'domain_id', avg_trust)

domains_df

,domain_name,domain_id,job_satisfaction,job_loss,consumer_trust
0,Software Engineering,1,NaN,NaN,NaN
1,Modern History,2,NaN,NaN,NaN
2,Data Science,3,NaN,NaN,NaN
3,Biology,4,NaN,NaN,NaN
4,Business Administration,5,NaN,NaN,NaN
5,Fine Arts,6,NaN,NaN,NaN
6,Marketing,7,6.073260,19.577895,58.671579
7,Manufacturing,8,6.044068,32.746111,58.272778
8,IT,9,6.010067,NaN,NaN
9,Education,10,6.030717,26.142353,51.650000
10,Healthcare,11,6.055556,25.579412,60.160588
11,Finance,12,5.923333,27.790000,56.180714
12,Retail,13,6.014760,21.846667,62.727619
13,Media,14,NaN,22.749032,61.759032
14,Legal,15,NaN,28.234118,57.789412
15,Automotive,16,NaN,28.916842,61.240000
16,Gaming,17,NaN,27.204074,61.342963

In [532]:
majors = student_life_df['major'].unique()
def get_category(domain_name):
        if domain_name in majors:
            return 'Major'
        else:
            return 'Industry'

domains_df['category'] = domains_df['domain_name'].apply(get_category)

domains_df

,domain_name,domain_id,job_satisfaction,job_loss,consumer_trust,category
0,Software Engineering,1,NaN,NaN,NaN,Major
1,Modern History,2,NaN,NaN,NaN,Major
2,Data Science,3,NaN,NaN,NaN,Major
3,Biology,4,NaN,NaN,NaN,Major
4,Business Administration,5,NaN,NaN,NaN,Major
5,Fine Arts,6,NaN,NaN,NaN,Major
6,Marketing,7,6.073260,19.577895,58.671579,Industry
7,Manufacturing,8,6.044068,32.746111,58.272778,Industry
8,IT,9,6.010067,NaN,NaN,Industry
9,Education,10,6.030717,26.142353,51.650000,Industry
10,Healthcare,11,6.055556,25.579412,60.160588,Industry
11,Finance,12,5.923333,27.790000,56.180714,Industry
12,Retail,13,6.014760,21.846667,62.727619,Industry
13,Media,14,NaN,22.749032,61.759032,Industry
14,Legal,15,NaN,28.234118,57.789412,Industry
15,Automotive,16,NaN,28.916842,61.240000,Industry
16,Gaming,17,NaN,27.204074,61.342963,Industry

In [533]:
students_df = student_life_df.drop(['major', 'ai_tool'], axis=1)
employees_df = jobs_df.drop('industry', axis=1)

In [534]:
conn = sqlite3.connect('../Data/ai_impact.db')

domains_df.to_sql('domains', conn, index=False, if_exists='replace')
ai_tools_df.to_sql('ai_tools', conn, index=False, if_exists='replace')
students_df.to_sql('students', conn, index=False, if_exists='replace')
employees_df.to_sql('employees', conn, index=False, if_exists='replace')

conn.commit()

print('Connected:', conn)

conn.close()

Connected: <sqlite3.Connection object at 0x0000019BCE1132E0>

In [535]:
with sqlite3.connect('../Data/ai_impact.db') as conn:
    cursor = conn.cursor()

    cursor.execute('''
        SELECT student_id, gpa_baseline, gpa_post_ai, ai_ethics_concern, career_confidence_score
        FROM students
        ORDER BY gpa_baseline desc;
    ''')

    results = cursor.fetchall()
    for row in results:
        print(row)

('STU-2302', 4.0, 4.0, 'Low', 4)
('STU-9020', 4.0, 4.0, 'Medium', 3)
('STU-6195', 4.0, 4.0, 'High', 5)
('STU-8701', 4.0, 4.0, 'Medium', 2)
('STU-3582', 4.0, 4.0, 'Low', 4)
('STU-6962', 3.99, 4.0, 'Medium', 4)
('STU-5643', 3.99, 4.0, 'High', 9)
('STU-1539', 3.99, 4.0, 'Low', 3)
('STU-4382', 3.99, 4.0, 'Medium', 2)
('STU-4331', 3.99, 3.89, 'Medium', 9)
('STU-5349', 3.99, 4.0, 'Low', 6)
('STU-9950', 3.99, 4.0, 'High', 6)
('STU-2253', 3.99, 4.0, 'High', 8)
('STU-4795', 3.99, 4.0, 'Low', 5)
('STU-6105', 3.99, 4.0, 'Medium', 10)
('STU-5976', 3.99, 4.0, 'Medium', 1)
('STU-8911', 3.99, 4.0, 'Medium', 6)
('STU-1609', 3.99, 4.0, 'Medium', 10)
('STU-4392', 3.99, 4.0, 'Low', 7)
('STU-9507', 3.98, 3.98, 'High', 7)
('STU-1230', 3.98, 3.88, 'Medium', 7)
('STU-6578', 3.98, 3.98, 'High', 4)
('STU-2210', 3.98, 3.98, 'High', 6)
('STU-7147', 3.98, 4.0, 'Medium', 1)
('STU-2901', 3.98, 3.88, 'Low', 8)
('STU-2902', 3.98, 3.98, 'Low', 1)
('STU-7322', 3.98, 4.0, 'Low', 10)
('STU-9692', 3.97, 4.0, 'High', 2)
('STU-8009', 3.97, 4.0, 'Low', 5)
('STU-2743', 3.97, 4.0, 'Medium', 8)
('STU-1993', 3.97, 4.0, 'Medium', 2)
('STU-4592', 3.97, 4.0, 'Low', 6)
('STU-7847', 3.97, 4.0, 'High', 6)
('STU-5180', 3.97, 3.97, 'Medium', 6)
('STU-2612', 3.97, 3.87, 'Low', 4)
('STU-9651', 3.97, 4.0, 'Medium', 8)
('STU-5307', 3.97, 4.0, 'High', 10)
('STU-5729', 3.97, 4.0, 'Medium', 5)
('STU-8588', 3.97, 4.0, 'High', 10)
('STU-6146', 3.97, 3.87, 'Medium', 10)
('STU-4687', 3.97, 4.0, 'Medium', 10)
('STU-6675', 3.97, 4.0, 'High', 5)
('STU-4779', 3.96, 3.96, 'Medium', 10)
('STU-6617', 3.96, 3.86, 'High', 9)
('STU-2303', 3.96, 4.0, 'Medium', 2)
('STU-6038', 3.96, 4.0, 'High', 4)
('STU-2609', 3.96, 3.86, 'High', 6)
('STU-5252', 3.96, 4.0, 'Medium', 4)
('STU-6276', 3.96, 4.0, 'Medium', 4)
('STU-8290', 3.96, 3.86, 'High', 1)
('STU-9560', 3.96, 4.0, 'Medium', 8)
('STU-0780', 3.96, 4.0, 'Medium', 9)
('STU-3479', 3.96, 3.86, 'Low', 6)
('STU-5322', 3.96, 4.0, 'Medium', 9)
('STU-9623', 3.95, 4.0, 'Low', 2)
('STU-6373', 3.95, 4.0, 'Low', 10)
('STU-4578', 3.95, 3.95, 'Medium', 2)
('STU-1747', 3.95, 3.85, 'Medium', 2)
('STU-3719', 3.95, 3.95, 'High', 7)
('STU-3425', 3.95, 4.0, 'High', 2)
('STU-7590', 3.95, 4.0, 'High', 10)
('STU-8845', 3.94, 4.0, 'High', 7)
('STU-8111', 3.94, 4.0, 'Low', 1)
('STU-9159', 3.94, 3.84, 'Low', 2)
('STU-1379', 3.94, 3.84, 'Low', 4)
('STU-4237', 3.94, 4.0, 'Medium', 10)
('STU-6397', 3.94, 4.0, 'Low', 3)
('STU-3156', 3.94, 4.0, 'High', 4)
('STU-7204', 3.94, 4.0, 'High', 4)
('STU-2457', 3.94, 3.84, 'Low', 1)
('STU-8870', 3.94, 3.84, 'Medium', 10)
('STU-5837', 3.94, 4.0, 'Medium', 6)
('STU-2572', 3.94, 3.84, 'Medium', 9)
('STU-5638', 3.94, 3.84, 'Medium', 6)
('STU-1540', 3.93, 4.0, 'Low', 9)
('STU-5793', 3.93, 3.83, 'High', 10)
('STU-0197', 3.93, 4.0, 'Medium', 1)
('STU-5987', 3.93, 4.0, 'Medium', 10)
('STU-3472', 3.93, 4.0, 'Medium', 1)
('STU-1558', 3.93, 3.93, 'Low', 7)
('STU-2738', 3.93, 4.0, 'Medium', 7)
('STU-9283', 3.93, 4.0, 'High', 9)
('STU-7312', 3.93, 3.93, 'High', 2)
('STU-7727', 3.93, 4.0, 'High', 8)
('STU-6891', 3.92, 4.0, 'High', 1)
('STU-4730', 3.92, 4.0, 'Medium', 9)
('STU-1099', 3.92, 3.82, 'Medium', 6)
('STU-6557', 3.92, 3.82, 'Low', 9)
('STU-0436', 3.92, 4.0, 'Medium', 9)
('STU-4693', 3.92, 4.0, 'High', 2)
('STU-3559', 3.92, 3.92, 'Low', 3)
('STU-4963', 3.92, 4.0, 'Medium', 5)
('STU-8065', 3.92, 4.0, 'High', 3)
('STU-9666', 3.92, 4.0, 'Medium', 5)
('STU-8608', 3.92, 4.0, 'Medium', 6)
('STU-0146', 3.92, 4.0, 'Medium', 2)
('STU-7927', 3.92, 4.0, 'High', 6)
('STU-3142', 3.92, 3.92, 'Low', 1)
('STU-2450', 3.92, 4.0, 'Medium', 4)
('STU-1687', 3.91, 3.81, 'Low', 5)
('STU-0704', 3.91, 4.0, 'Medium', 10)
('STU-9720', 3.91, 3.91, 'High', 7)
('STU-0634', 3.91, 4.0, 'High', 5)
('STU-0598', 3.91, 3.91, 'Medium', 6)
('STU-2877', 3.91, 4.0, 'Medium', 2)
('STU-1374', 3.9, 4.0, 'Low', 3)
('STU-4589', 3.9, 3.8, 'Low', 9)
('STU-9210', 3.9, 4.0, 'High', 5)
('STU-8650', 3.9, 4.0, 'High', 7)
('STU-4099', 3.9, 4.0, 'Medium', 10)
('STU-3489', 3.9, 4.0, 'Medium', 4)
('STU-7768', 3.9, 4.0, 'Low', 5)
('STU-9940', 3.9, 4.0, 'High', 9)
('STU-6181', 3.9, 4.0, 'Medium', 7)
('STU-1425', 3.9, 3.9, 'Low', 6)
('STU-3524', 3.9, 4.0, 'Low', 9)
('STU-3853', 3.9, 3.8, 'High', 6)
('STU-4991', 3.9, 4.0, 'High', 6)
('STU-0860', 3.9, 3.9, 'High', 8)
('STU-6690', 3.9, 4.0, 'Medium', 3)
('STU-0257', 3.9, 3.9, 'Low', 3)
('STU-4321', 3.89, 4.0, 'Medium', 2)
('STU-0300', 3.89, 3.79, 'Low', 3)
('STU-5071', 3.89, 3.89, 'Low', 4)
('STU-5127', 3.89, 3.89, 'High', 6)
('STU-7692', 3.89, 3.79, 'High', 4)
('STU-3684', 3.89, 3.79, 'Medium', 5)
('STU-8260', 3.89, 4.0, 'Medium', 5)
('STU-5272', 3.89, 3.99, 'High', 10)
('STU-8025', 3.89, 3.89, 'Low', 9)
('STU-3252', 3.89, 4.0, 'High', 3)
('STU-0820', 3.89, 3.99, 'High', 5)
('STU-2921', 3.89, 4.0, 'Medium', 2)
('STU-0880', 3.89, 3.99, 'Medium', 8)
('STU-3267', 3.89, 4.0, 'High', 9)
('STU-1108', 3.89, 3.89, 'Medium', 1)
('STU-9129', 3.89, 3.89, 'Low', 2)
('STU-1277', 3.88, 3.88, 'Low', 5)
('STU-6001', 3.88, 3.98, 'High', 1)
('STU-3504', 3.88, 3.88, 'Low', 2)
('STU-5042', 3.88, 4.0, 'Medium', 10)
('STU-4455', 3.88, 3.98, 'High', 10)
('STU-3438', 3.88, 3.78, 'Medium', 8)
('STU-0010', 3.88, 4.0, 'High', 4)
('STU-4953', 3.87, 3.97, 'Low', 1)
('STU-0497', 3.87, 3.77, 'Low', 1)
('STU-5466', 3.87, 3.87, 'Medium', 6)
('STU-9364', 3.87, 4.0, 'Low', 7)
('STU-9105', 3.87, 3.77, 'High', 9)
('STU-7616', 3.87, 3.77, 'Medium', 8)
('STU-6301', 3.87, 3.97, 'Medium', 6)
('STU-3416', 3.87, 4.0, 'Low', 8)
('STU-6357', 3.87, 4.0, 'High', 7)
('STU-2017', 3.87, 3.97, 'Medium', 8)
('STU-6300', 3.87, 4.0, 'High', 1)
('STU-9793', 3.86, 4.0, 'Low', 2)
('STU-5652', 3.86, 3.76, 'High', 10)
('STU-2732', 3.86, 3.86, 'Low', 9)
('STU-6203', 3.86, 3.86, 'High', 5)
('STU-1460', 3.86, 4.0, 'High', 8)
('STU-5067', 3.86, 4.0, 'High', 4)
('STU-8751', 3.86, 4.0, 'High', 6)
('STU-7247', 3.86, 4.0, 'Medium', 4)
('STU-4105', 3.86, 4.0, 'High', 1)
('STU-3626', 3.86, 3.96, 'Medium', 3)
('STU-6685', 3.85, 3.85, 'Medium', 1)
('STU-9799', 3.85, 4.0, 'Medium', 2)
('STU-8473', 3.85, 3.85, 'Low', 2)
('STU-0190', 3.85, 4.0, 'High', 9)
('STU-4839', 3.85, 4.0, 'Low', 8)
('STU-7241', 3.84, 3.74, 'Medium', 2)
('STU-0939', 3.84, 3.74, 'Medium', 9)
('STU-6004', 3.84, 4.0, 'Low', 8)
('STU-4965', 3.84, 3.84, 'Low', 2)
('STU-3677', 3.84, 4.0, 'Low', 8)
('STU-8828', 3.84, 4.0, 'Low', 1)
('STU-4227', 3.84, 4.0, 'Medium', 1)
('STU-4929', 3.84, 3.84, 'Low', 10)
('STU-7976', 3.83, 4.0, 'Low', 8)
('STU-1844', 3.83, 3.83, 'High', 6)
('STU-9914', 3.83, 4.0, 'Low', 5)
('STU-7494', 3.83, 3.73, 'High', 2)
('STU-3832', 3.82, 3.72, 'Medium', 9)
('STU-2000', 3.82, 4.0, 'High', 5)
('STU-0067', 3.82, 3.92, 'Medium', 9)
('STU-1949', 3.82, 4.0, 'Low', 4)
('STU-8121', 3.82, 3.72, 'Medium', 3)
('STU-5999', 3.82, 3.92, 'Medium', 3)
('STU-4188', 3.82, 3.82, 'High', 5)
('STU-7169', 3.82, 3.72, 'High', 2)
('STU-9665', 3.82, 4.0, 'Low', 6)
('STU-3697', 3.82, 4.0, 'High', 1)
('STU-9776', 3.81, 4.0, 'Low', 1)
('STU-8502', 3.81, 3.91, 'High', 4)
('STU-1636', 3.81, 3.91, 'Medium', 3)
('STU-2956', 3.81, 3.81, 'Low', 1)
('STU-6308', 3.81, 3.71, 'Low', 2)
('STU-9828', 3.81, 4.0, 'High', 8)
('STU-7773', 3.81, 3.71, 'Low', 1)
('STU-1302', 3.81, 3.91, 'Low', 4)
('STU-2586', 3.8, 3.8, 'Low', 2)
('STU-5931', 3.8, 4.0, 'Medium', 2)
('STU-6732', 3.8, 3.7, 'High', 4)
('STU-7712', 3.8, 3.7, 'Low', 5)
('STU-6246', 3.8, 4.0, 'High', 5)
('STU-1873', 3.8, 4.0, 'High', 1)
('STU-5901', 3.8, 3.7, 'High', 7)
('STU-1323', 3.8, 4.0, 'High', 1)
('STU-7974', 3.8, 4.0, 'Medium', 5)
('STU-4825', 3.8, 4.0, 'Low', 8)
('STU-3592', 3.8, 3.8, 'High', 3)
('STU-0656', 3.8, 4.0, 'Medium', 8)
('STU-8611', 3.8, 3.8, 'Low', 2)
('STU-3546', 3.8, 3.7, 'High', 9)
('STU-3512', 3.79, 4.0, 'High', 9)
('STU-0482', 3.79, 3.79, 'Low', 10)
('STU-6482', 3.79, 3.79, 'High', 3)
('STU-7683', 3.79, 4.0, 'Medium', 8)
('STU-5491', 3.79, 3.89, 'High', 4)
('STU-3615', 3.79, 3.69, 'Low', 8)
('STU-9663', 3.79, 4.0, 'Low', 7)
('STU-5289', 3.79, 3.69, 'Medium', 4)
('STU-2179', 3.79, 3.99, 'Low', 7)
('STU-3060', 3.79, 3.99, 'High', 3)
('STU-6975', 3.79, 4.0, 'High', 8)
('STU-6823', 3.78, 3.68, 'High', 3)
('STU-2531', 3.78, 4.0, 'High', 8)
('STU-6475', 3.78, 3.68, 'Medium', 1)
('STU-9648', 3.78, 4.0, 'High', 3)
('STU-6977', 3.78, 3.98, 'Medium', 8)
('STU-4488', 3.78, 3.98, 'Medium', 5)
('STU-8493', 3.78, 3.88, 'Low', 10)
('STU-7664', 3.78, 3.78, 'Low', 10)
('STU-3453', 3.78, 3.78, 'Medium', 7)
('STU-2160', 3.78, 3.78, 'High', 9)
('STU-8812', 3.78, 3.68, 'Low', 8)
('STU-4364', 3.78, 3.98, 'High', 5)
('STU-5842', 3.77, 3.87, 'Low', 5)
('STU-4656', 3.77, 4.0, 'High', 8)
('STU-7336', 3.77, 3.87, 'High', 9)
('STU-4664', 3.77, 3.97, 'High', 6)
('STU-2686', 3.77, 3.87, 'Low', 5)
('STU-7497', 3.77, 3.87, 'High', 7)
('STU-3157', 3.77, 3.67, 'High', 1)
('STU-1670', 3.77, 3.87, 'Low', 10)
('STU-0879', 3.77, 3.87, 'Medium', 9)
('STU-9626', 3.77, 3.87, 'Medium', 4)
('STU-9292', 3.77, 3.87, 'Low', 4)
('STU-8144', 3.77, 4.0, 'High', 7)
('STU-5445', 3.77, 4.0, 'Low', 1)
('STU-5726', 3.77, 3.87, 'Medium', 2)
('STU-9579', 3.76, 3.66, 'Low', 5)
('STU-3321', 3.76, 3.86, 'Low', 7)
('STU-8187', 3.76, 3.66, 'High', 3)
('STU-8897', 3.76, 3.66, 'High', 7)
('STU-0369', 3.76, 3.66, 'Low', 2)
('STU-8024', 3.76, 4.0, 'High', 4)
('STU-6810', 3.76, 3.76, 'Low', 7)
('STU-2341', 3.76, 3.76, 'Low', 10)
('STU-1436', 3.76, 3.66, 'Medium', 10)
('STU-1911', 3.76, 3.96, 'Low', 9)
('STU-5860', 3.75, 3.65, 'High', 2)
('STU-1927', 3.75, 3.95, 'Medium', 7)
('STU-7397', 3.75, 3.75, 'High', 3)
('STU-8657', 3.74, 3.64, 'Low', 7)
('STU-5452', 3.74, 3.64, 'Medium', 10)
('STU-3855', 3.74, 4.0, 'Medium', 3)
('STU-1704', 3.74, 3.84, 'Low', 7)
('STU-9229', 3.74, 3.94, 'High', 3)
('STU-9361', 3.74, 3.94, 'High', 2)
('STU-3544', 3.74, 3.64, 'Medium', 6)
('STU-1187', 3.74, 3.94, 'Medium', 3)
('STU-9823', 3.74, 3.94, 'Low', 3)
('STU-7164', 3.74, 4.0, 'Medium', 1)
('STU-7657', 3.74, 3.64, 'Medium', 4)
('STU-8851', 3.73, 4.0, 'High', 8)
('STU-8786', 3.73, 3.83, 'High', 10)
('STU-0289', 3.73, 4.0, 'Low', 6)
('STU-2899', 3.73, 3.83, 'Medium', 10)
('STU-5088', 3.73, 3.73, 'Low', 4)
('STU-4535', 3.73, 3.93, 'Medium', 5)
('STU-0231', 3.72, 3.82, 'High', 8)
('STU-6236', 3.72, 3.72, 'Medium', 10)
('STU-2117', 3.72, 4.0, 'Medium', 5)
('STU-4346', 3.72, 3.92, 'High', 1)
('STU-2873', 3.72, 3.62, 'Low', 4)
('STU-3571', 3.71, 3.61, 'Medium', 6)
('STU-4537', 3.71, 3.81, 'Low', 3)
('STU-9187', 3.71, 3.61, 'Medium', 9)
('STU-0135', 3.71, 3.71, 'High', 5)
('STU-9679', 3.71, 3.81, 'Medium', 9)
('STU-1883', 3.71, 3.71, 'Low', 1)
('STU-0464', 3.71, 3.71, 'High', 4)
('STU-2607', 3.71, 3.71, 'Medium', 4)
('STU-6262', 3.71, 3.61, 'Low', 5)
('STU-4804', 3.71, 3.81, 'High', 9)
('STU-6252', 3.7, 3.7, 'Low', 1)
('STU-4576', 3.7, 3.8, 'Low', 1)
('STU-2712', 3.7, 3.6, 'High', 7)
('STU-7509', 3.7, 3.6, 'Low', 6)
('STU-8487', 3.7, 3.8, 'High', 9)
('STU-6342', 3.7, 3.6, 'High', 1)
('STU-7327', 3.7, 3.8, 'High', 6)
('STU-9841', 3.7, 3.9, 'High', 10)
('STU-0702', 3.7, 3.8, 'Low', 8)
('STU-4879', 3.7, 3.7, 'Low', 6)
('STU-1284', 3.69, 3.89, 'Medium', 8)
('STU-8441', 3.69, 3.79, 'Low', 10)
('STU-2518', 3.69, 3.89, 'High', 10)
('STU-9997', 3.69, 3.89, 'Low', 10)
('STU-2397', 3.69, 3.79, 'Low', 3)
('STU-1565', 3.69, 3.89, 'Medium', 4)
('STU-9987', 3.69, 3.99, 'Medium', 10)
('STU-9877', 3.69, 3.79, 'High', 6)
('STU-6820', 3.69, 3.79, 'Low', 6)
('STU-4207', 3.69, 3.89, 'Medium', 9)
('STU-9040', 3.68, 3.58, 'Low', 10)
('STU-6949', 3.68, 3.98, 'Medium', 4)
('STU-2250', 3.68, 3.58, 'Low', 3)
('STU-8134', 3.68, 3.78, 'Medium', 4)
('STU-2024', 3.68, 3.68, 'Low', 2)
('STU-1960', 3.67, 3.67, 'High', 2)
('STU-7730', 3.67, 3.87, 'High', 1)
('STU-5476', 3.67, 3.77, 'Low', 10)
('STU-1896', 3.67, 3.97, 'Medium', 10)
('STU-3927', 3.67, 3.77, 'Medium', 4)
('STU-7313', 3.67, 3.87, 'Medium', 2)
('STU-5780', 3.67, 3.97, 'High', 2)
('STU-2807', 3.67, 3.77, 'High', 6)
('STU-8176', 3.67, 3.67, 'Medium', 3)
('STU-1224', 3.67, 3.77, 'High', 1)
('STU-0989', 3.67, 3.97, 'High', 4)
('STU-3107', 3.66, 3.76, 'Low', 9)
('STU-1920', 3.66, 3.86, 'High', 2)
('STU-9034', 3.66, 3.86, 'Low', 5)
('STU-4552', 3.66, 3.76, 'Low', 3)
('STU-7909', 3.66, 3.76, 'High', 6)
('STU-1779', 3.66, 3.76, 'Medium', 10)
('STU-5454', 3.66, 3.96, 'Medium', 6)
('STU-1837', 3.65, 3.85, 'High', 9)
('STU-8893', 3.65, 3.55, 'Medium', 4)
('STU-4987', 3.65, 3.55, 'Medium', 9)
('STU-6881', 3.65, 3.95, 'High', 7)
('STU-4946', 3.65, 3.85, 'Low', 4)
('STU-5276', 3.65, 3.85, 'Medium', 3)
('STU-4954', 3.65, 3.55, 'Low', 2)
('STU-3192', 3.65, 3.85, 'High', 7)
('STU-4928', 3.65, 3.55, 'Low', 4)
('STU-7329', 3.65, 3.95, 'Low', 2)
('STU-6524', 3.65, 3.75, 'High', 4)
('STU-3474', 3.64, 3.84, 'Low', 3)
('STU-6932', 3.64, 3.74, 'High', 10)
('STU-3875', 3.64, 3.64, 'High', 4)
('STU-2517', 3.64, 3.74, 'High', 10)
('STU-4056', 3.64, 3.54, 'Low', 1)
('STU-0973', 3.64, 3.84, 'High', 7)
('STU-5382', 3.64, 3.64, 'Low', 7)
('STU-6427', 3.64, 3.54, 'Low', 6)
('STU-8117', 3.63, 3.63, 'Medium', 8)
('STU-6813', 3.63, 3.63, 'Low', 1)
('STU-8259', 3.63, 3.83, 'High', 7)
('STU-1279', 3.63, 3.63, 'Low', 6)
('STU-1271', 3.63, 3.83, 'High', 1)
('STU-9455', 3.63, 3.73, 'Low', 1)
('STU-3234', 3.63, 3.93, 'Medium', 4)
('STU-2872', 3.63, 3.73, 'Medium', 6)
('STU-7899', 3.63, 3.63, 'Medium', 9)
('STU-6762', 3.63, 3.63, 'High', 10)
('STU-7838', 3.62, 3.62, 'Low', 9)
('STU-1294', 3.62, 3.82, 'High', 2)
('STU-7609', 3.62, 3.72, 'Low', 8)
('STU-1221', 3.62, 3.92, 'Low', 4)
('STU-6639', 3.62, 3.92, 'Medium', 2)
('STU-7273', 3.62, 3.52, 'Low', 9)
('STU-0386', 3.62, 3.62, 'High', 8)
('STU-4146', 3.62, 3.62, 'Medium', 4)
('STU-2123', 3.61, 3.71, 'High', 10)
('STU-4290', 3.61, 3.51, 'Low', 4)
('STU-2760', 3.61, 3.91, 'Low', 6)
('STU-5521', 3.61, 3.51, 'Low', 6)
('STU-6554', 3.61, 3.71, 'Medium', 8)
('STU-3452', 3.61, 3.61, 'Medium', 1)
('STU-6585', 3.61, 3.71, 'Low', 7)
('STU-5231', 3.6, 3.6, 'High', 6)
('STU-9676', 3.6, 3.5, 'High', 7)
('STU-4966', 3.6, 3.7, 'Low', 5)
('STU-3328', 3.6, 3.9, 'High', 5)
('STU-0324', 3.6, 3.7, 'Medium', 8)
('STU-1635', 3.6, 3.9, 'Medium', 7)
('STU-0897', 3.6, 3.8, 'Low', 5)
('STU-6273', 3.6, 3.6, 'Medium', 5)
('STU-6116', 3.6, 3.6, 'Medium', 4)
('STU-6440', 3.6, 3.8, 'Medium', 4)
('STU-4144', 3.6, 3.7, 'High', 7)
('STU-0866', 3.6, 3.8, 'Medium', 3)
('STU-0858', 3.59, 3.59, 'Low', 7)
('STU-6230', 3.59, 3.79, 'High', 9)
('STU-3087', 3.59, 3.69, 'High', 5)
('STU-4274', 3.59, 3.49, 'Low', 4)
('STU-6602', 3.59, 3.59, 'High', 3)
('STU-7478', 3.59, 3.79, 'Low', 1)
('STU-4010', 3.59, 3.59, 'Medium', 8)
('STU-3348', 3.59, 3.69, 'Medium', 4)
('STU-4888', 3.59, 3.89, 'Medium', 7)
('STU-1936', 3.58, 3.68, 'Medium', 5)
('STU-2779', 3.58, 3.78, 'High', 6)
('STU-3184', 3.58, 3.78, 'High', 1)
('STU-7610', 3.58, 3.68, 'Medium', 5)
('STU-3550', 3.58, 3.88, 'Low', 10)
('STU-0396', 3.58, 3.58, 'Low', 9)
('STU-2130', 3.58, 3.48, 'Medium', 8)
('STU-3791', 3.58, 3.68, 'Medium', 5)
('STU-8381', 3.58, 3.58, 'High', 2)
('STU-1894', 3.58, 3.48, 'Medium', 2)
('STU-2606', 3.58, 3.48, 'Low', 1)
('STU-3461', 3.58, 3.48, 'High', 2)
('STU-5367', 3.57, 3.67, 'High', 4)
('STU-1697', 3.57, 3.67, 'High', 10)
('STU-9212', 3.57, 3.87, 'Medium', 6)
('STU-5051', 3.57, 3.47, 'Medium', 9)
('STU-7767', 3.57, 3.57, 'Low', 8)
('STU-6180', 3.57, 3.67, 'Medium', 7)
('STU-1479', 3.57, 3.47, 'Low', 8)
('STU-2814', 3.57, 3.47, 'Low', 10)
('STU-8455', 3.57, 3.47, 'Low', 5)
('STU-5187', 3.57, 3.47, 'High', 2)
('STU-2320', 3.57, 3.47, 'Low', 7)
('STU-0256', 3.57, 3.67, 'Medium', 9)
('STU-1262', 3.56, 3.66, 'Low', 8)
('STU-8790', 3.56, 3.86, 'Low', 8)
('STU-8888', 3.56, 3.46, 'High', 2)
('STU-1092', 3.56, 3.76, 'Medium', 4)
('STU-4661', 3.56, 3.56, 'Medium', 10)
('STU-3135', 3.56, 3.86, 'Medium', 3)
('STU-3257', 3.56, 3.86, 'Medium', 1)
('STU-5388', 3.56, 3.46, 'Medium', 6)
('STU-6394', 3.55, 3.75, 'Low', 4)
('STU-1346', 3.55, 3.85, 'High', 6)
('STU-1820', 3.55, 3.45, 'High', 8)
('STU-0589', 3.55, 3.55, 'Medium', 7)
('STU-7947', 3.55, 3.85, 'High', 1)
('STU-0134', 3.55, 3.75, 'High', 8)
('STU-4570', 3.55, 3.85, 'Medium', 3)
('STU-2714', 3.55, 3.55, 'Low', 8)
('STU-4170', 3.55, 3.85, 'High', 3)
('STU-7512', 3.55, 3.65, 'High', 9)
('STU-4838', 3.54, 3.64, 'High', 3)
('STU-7668', 3.54, 3.74, 'Low', 3)
('STU-1003', 3.54, 3.44, 'Low', 2)
('STU-6856', 3.54, 3.64, 'Low', 10)
('STU-4484', 3.54, 3.84, 'Low', 2)
('STU-6644', 3.54, 3.54, 'Medium', 6)
('STU-0540', 3.53, 3.53, 'High', 7)
('STU-5543', 3.53, 3.43, 'Low', 2)
('STU-1158', 3.53, 3.53, 'Low', 7)
('STU-2683', 3.53, 3.53, 'Low', 2)
('STU-3839', 3.53, 3.63, 'High', 1)
('STU-7440', 3.53, 3.63, 'High', 2)
('STU-3722', 3.53, 3.63, 'High', 1)
('STU-4356', 3.53, 3.43, 'High', 5)
('STU-4999', 3.53, 3.53, 'High', 5)
('STU-4702', 3.53, 3.43, 'Medium', 8)
('STU-7965', 3.52, 3.62, 'High', 10)
('STU-2937', 3.52, 3.82, 'Medium', 8)
('STU-3056', 3.52, 3.82, 'Medium', 4)
('STU-6503', 3.52, 3.72, 'High', 7)
('STU-4974', 3.52, 3.72, 'High', 2)
('STU-5488', 3.52, 3.42, 'Low', 2)
('STU-5245', 3.51, 3.81, 'Low', 2)
('STU-2974', 3.51, 3.51, 'High', 8)
('STU-9323', 3.51, 3.71, 'High', 4)
('STU-8073', 3.51, 3.61, 'Low', 2)
('STU-7065', 3.51, 3.81, 'Low', 4)
('STU-6927', 3.51, 3.51, 'High', 1)
('STU-0698', 3.51, 3.71, 'High', 4)
('STU-6907', 3.51, 3.61, 'High', 9)
('STU-9757', 3.5, 3.4, 'High', 7)
('STU-3405', 3.5, 3.4, 'Medium', 1)
('STU-9411', 3.5, 3.5, 'High', 9)
('STU-7323', 3.5, 3.5, 'Low', 5)
('STU-4659', 3.5, 3.4, 'Medium', 3)
('STU-4608', 3.5, 3.8, 'Low', 9)
('STU-4805', 3.5, 3.4, 'High', 3)
('STU-0531', 3.5, 3.4, 'Low', 10)
('STU-1806', 3.5, 3.7, 'Medium', 6)
('STU-1324', 3.5, 3.8, 'Medium', 1)
('STU-7744', 3.5, 3.4, 'High', 10)
('STU-8986', 3.5, 3.8, 'Medium', 2)
('STU-3538', 3.49, 3.39, 'Medium', 4)
('STU-8451', 3.49, 3.49, 'High', 3)
('STU-7121', 3.49, 3.5900000000000003, 'Medium', 6)
('STU-2544', 3.49, 3.39, 'Low', 9)
('STU-4320', 3.49, 3.49, 'Low', 7)
('STU-9305', 3.49, 3.49, 'Low', 9)
('STU-0121', 3.49, 3.49, 'Medium', 1)
('STU-9025', 3.49, 3.69, 'Low', 9)
('STU-9699', 3.49, 3.5900000000000003, 'High', 10)
('STU-7865', 3.49, 3.69, 'Medium', 3)
('STU-1244', 3.49, 3.49, 'High', 5)
('STU-2784', 3.49, 3.49, 'High', 10)
('STU-6620', 3.49, 3.5900000000000003, 'Medium', 4)
('STU-4761', 3.49, 3.69, 'Medium', 6)
('STU-0237', 3.49, 3.39, 'Low', 5)
('STU-5360', 3.48, 3.48, 'Medium', 5)
('STU-2113', 3.48, 3.68, 'Low', 7)
('STU-8148', 3.48, 3.48, 'Low', 3)
('STU-1087', 3.48, 3.38, 'High', 10)
('STU-9415', 3.48, 3.38, 'High', 7)
('STU-8543', 3.48, 3.78, 'Medium', 8)
('STU-4880', 3.48, 3.48, 'Medium', 6)
('STU-0349', 3.48, 3.78, 'High', 3)
('STU-4866', 3.48, 3.78, 'Medium', 2)
('STU-5701', 3.48, 3.58, 'Low', 2)
('STU-0095', 3.48, 3.78, 'Low', 3)
('STU-1624', 3.48, 3.68, 'Low', 1)
('STU-8378', 3.47, 3.47, 'Medium', 8)
('STU-3013', 3.47, 3.77, 'High', 3)
('STU-4912', 3.47, 3.77, 'Medium', 3)
('STU-9830', 3.47, 3.67, 'Medium', 9)
('STU-6774', 3.47, 3.67, 'Medium', 8)
('STU-2625', 3.47, 3.5700000000000003, 'Medium', 6)
('STU-0821', 3.47, 3.5700000000000003, 'Low', 4)
('STU-0627', 3.47, 3.37, 'High', 5)
('STU-3892', 3.47, 3.37, 'Medium', 2)
('STU-4811', 3.46, 3.76, 'Medium', 8)
('STU-5002', 3.46, 3.46, 'Low', 4)
('STU-6162', 3.46, 3.76, 'Low', 6)
('STU-1750', 3.46, 3.36, 'Medium', 1)
('STU-9256', 3.46, 3.76, 'Low', 10)
('STU-3532', 3.46, 3.66, 'Medium', 5)
('STU-3233', 3.46, 3.56, 'High', 2)
('STU-4254', 3.46, 3.66, 'Low', 8)
('STU-9805', 3.46, 3.66, 'Medium', 3)
('STU-7516', 3.46, 3.76, 'Low', 9)
('STU-6704', 3.46, 3.46, 'High', 4)
('STU-2382', 3.46, 3.46, 'Low', 7)
('STU-8438', 3.46, 3.46, 'Low', 3)
('STU-4002', 3.45, 3.65, 'High', 8)
('STU-5728', 3.45, 3.65, 'High', 7)
('STU-8015', 3.45, 3.75, 'Medium', 8)
('STU-6126', 3.45, 3.75, 'Low', 1)
('STU-3899', 3.45, 3.75, 'High', 1)
('STU-2383', 3.45, 3.75, 'High', 9)
('STU-8991', 3.45, 3.45, 'Medium', 1)
('STU-1392', 3.45, 3.35, 'Low', 7)
('STU-4994', 3.45, 3.65, 'Medium', 4)
('STU-3395', 3.45, 3.75, 'High', 6)
('STU-8423', 3.45, 3.65, 'High', 5)
('STU-9197', 3.44, 3.54, 'High', 7)
('STU-6681', 3.44, 3.74, 'Low', 1)
('STU-5326', 3.44, 3.44, 'High', 4)
('STU-0850', 3.44, 3.74, 'Low', 1)
('STU-4334', 3.44, 3.34, 'Medium', 5)

In [536]:
with sqlite3.connect('../Data/ai_impact.db') as conn:
    cursor = conn.cursor()

    cursor.execute('''
        SELECT *
        FROM domains;
    ''')

    results = cursor.fetchall()
    for row in results:
        print(row)

('Software Engineering', 1, None, None, None, 'Major')
('Modern History', 2, None, None, None, 'Major')
('Data Science', 3, None, None, None, 'Major')
('Biology', 4, None, None, None, 'Major')
('Business Administration', 5, None, None, None, 'Major')
('Fine Arts', 6, None, None, None, 'Major')
('Marketing', 7, 6.073260073260073, 19.577894736842108, 58.671578947368424, 'Industry')
('Manufacturing', 8, 6.04406779661017, 32.74611111111111, 58.27277777777778, 'Industry')
('IT', 9, 6.010067114093959, None, None, 'Industry')
('Education', 10, 6.030716723549488, 26.142352941176473, 51.65, 'Industry')
('Healthcare', 11, 6.055555555555555, 25.579411764705885, 60.16058823529412, 'Industry')
('Finance', 12, 5.923333333333333, 27.79, 56.18071428571428, 'Industry')
('Retail', 13, 6.014760147601476, 21.846666666666664, 62.727619047619044, 'Industry')
('Media', 14, None, 22.749032258064517, 61.759032258064515, 'Industry')
('Legal', 15, None, 28.234117647058824, 57.78941176470588, 'Industry')
('Automotive', 16, None, 28.916842105263157, 61.239999999999995, 'Industry')
('Gaming', 17, None, 27.204074074074075, 61.342962962962964, 'Industry')

In [537]:
query = ''' SELECT
    job_loss, domain_name
    FROM domains
    ORDER BY job_loss desc
'''
result = pd.read_sql(query, conn)
result

     job_loss              domain_name
0   32.746111            Manufacturing
1   28.916842               Automotive
2   28.234118                    Legal
3   27.790000                  Finance
4   27.204074                   Gaming
5   26.142353                Education
6   25.579412               Healthcare
7   22.749032                    Media
8   21.846667                   Retail
9   19.577895                Marketing
10        NaN     Software Engineering
11        NaN           Modern History
12        NaN             Data Science
13        NaN                  Biology
14        NaN  Business Administration
15        NaN                Fine Arts
16        NaN                       IT

In [562]:
query = ''' 
    SELECT
        s.main_usage_case,
        COUNT(s.main_usage_case) as number_of_cases,
        a.ai_tool
    FROM students s
    JOIN ai_tools a on a.ai_tool_id = s.ai_tool_id
    GROUP BY s.main_usage_case, a.ai_tool
    ORDER BY number_of_cases desc
    '''
result = pd.read_sql(query, conn)
result

      main_usage_case  number_of_cases         ai_tool
0           Exam Prep               87      Gemini Pro
1   Literature Review               74          Claude
2      Essay Drafting               72      Perplexity
3   Literature Review               71  GitHub Copilot
4           Exam Prep               69         ChatGPT
5           Exam Prep               68          Claude
6       Brainstorming               65      Gemini Pro
7       Brainstorming               63  GitHub Copilot
8      Essay Drafting               63         ChatGPT
9   Literature Review               60      Perplexity
10     Code Debugging               59  GitHub Copilot
11     Essay Drafting               59  GitHub Copilot
12          Exam Prep               59  GitHub Copilot
13     Code Debugging               58      Perplexity
14          Exam Prep               58      Perplexity
15     Essay Drafting               55          Claude
16  Literature Review               55         ChatGPT
17      Brainstorming               54      Perplexity
18      Brainstorming               52         ChatGPT
19      Brainstorming               52          Claude
20     Essay Drafting               52      Gemini Pro
21     Code Debugging               50      Gemini Pro
22     Code Debugging               49         ChatGPT
23     Code Debugging               48          Claude
24  Literature Review               48      Gemini Pro

In [ ]:
query = ''' 
    SELECT
        
    FROM ai_tools
    '''
result = pd.read_sql(query, conn)
result

            ai_tool  ai_tool_id
0        Gemini Pro           1
1    GitHub Copilot           2
2        Perplexity           3
3            Claude           4
4           ChatGPT           5
5              Bard           6
6            DALL-E           7
7  Stable Diffusion           8
8        Midjourney           9
9         Synthesia          10