In [ ]:
import pandas as pd

In [ ]:
student_life_df = pd.read_csv('../Data/AI_Impact_Student_Life_2026.csv')
jobs_df = pd.read_csv('../Data/ai_job_impact.csv')
content_df = pd.read_csv('../Data/Global_AI_Content_Impact_Dataset.csv')

In [40]:
student_life_df.head()

,Student_ID,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score
0,STU-6019,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3
1,STU-6962,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4
2,STU-2338,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7
3,STU-1380,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5
4,STU-1837,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9

In [ ]:
student_life_df.tail(10)

In [ ]:
student_life_df.info()

In [ ]:
student_life_df.shape

In [ ]:
jobs_df.head()

In [ ]:
jobs_df.tail()

In [ ]:
jobs_df.info()

In [ ]:
jobs_df.shape

In [ ]:
content_df.head()

In [ ]:
content_df.tail()

In [ ]:
content_df.info()

In [ ]:
content_df.shape

In [ ]:
student_life_df[['GPA_Baseline', 'GPA_Post_AI']]

In [ ]:
GPA_growth_df = student_life_df[student_life_df['GPA_Baseline'] < student_life_df['GPA_Post_AI']]
GPA_growth_df.shape

In [ ]:
GPA_decline_df = student_life_df[student_life_df['GPA_Baseline'] > student_life_df['GPA_Post_AI']]
GPA_decline_df.shape

In [ ]:
GPA_same_df = student_life_df[student_life_df['GPA_Baseline'] == student_life_df['GPA_Post_AI']]
GPA_same_df.shape

In [37]:
student_life_df.describe()

,Age,Task_Frequency_Daily,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,Career_Confidence_Score
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000,1500.000000
mean,21.494000,5.407333,3.256853,3.344587,8.51000,5.417333
std,2.297277,2.905462,0.430583,0.437409,4.07148,2.844977
min,18.000000,1.000000,2.500000,2.400000,2.00000,1.000000
25%,20.000000,3.000000,2.880000,2.980000,5.00000,3.000000
50%,21.000000,5.000000,3.260000,3.360000,9.00000,5.000000
75%,23.000000,8.000000,3.620000,3.710000,12.00000,8.000000
max,25.000000,10.000000,4.000000,4.000000,15.00000,10.000000

In [41]:
student_life_df['Primary_AI_Tool'].value_counts()

Primary_AI_Tool
GitHub Copilot    311
Gemini Pro        302
Perplexity        302
Claude 3.5        297
ChatGPT-4o        288
Name: count, dtype: int64